### ISSUE TITLE
Issues With CyberPunk 2077

### ISSUE THREAD

**Issue by kkthebeast** [luluco250/FXShaders#4]
https://i.imgur.com/XNgMdm5.jpg
depth only working on bottom half of screen
Thanks for your hard work!

**Comment by luluco250** [comment]
Does the output of DisplayDepth have the same problem?
If it does, you'll need to fix the depth buffer first.

**Comment by kkthebeast** [comment]
Sorry Ill check sir, brb

update:
[https://i.imgur.com/904pd0l.jpg](url)
Toggled the defaults in global. the default is half useable :P 

Do you have any tips on how to fiddle with it more. Or is this a wait for Reshade update or impossible thing :)

Thanks for your help 👍

**Comment by luluco250** [comment]
It seems like it's more than just the bottom half of the depth buffer that has issues, there are appears to be some precision problems as well:
![image](https://user-images.githubusercontent.com/18670927/103083538-6758b600-45bb-11eb-8681-eb39c221ebc9.png)

It may be worth checking in the ReShade forum or Discord for help (links in the [wiki](https://www.pcgamingwiki.com/wiki/ReShade)), see what other users have been doing with the game.

I'll be closing this issue for now since it seems like a depth buffer problem and not specific to Flashlight.fx
